// <auto-generated />
using System;
using FoodE_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodE_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260302052959_AddPreparedStockToFoodItem")]
    partial class AddPreparedStockToFoodItem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodE_Backend.Model.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DirectPurchaseCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDirectPurchase")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PreparedStock")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitMargin")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Burger",
                            Description = "Juicy beef patty with fresh vegetables and special sauce",
                            ImageUrl = "/images/burger.jpg",
                            IsAvailable = true,
                            IsDeal = false,
                            IsDirectPurchase = false,
                            Name = "Classic Beef Burger",
                            PreparedStock = 0,
                            Price = 0m,
                            ProfitMargin = 0m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Chicken Fry",
                            Description = "Golden fried chicken pieces with herbs and spices",
                            ImageUrl = "/images/chicken.jpg",
                            IsAvailable = true,
                            IsDeal = false,
                            IsDirectPurchase = false,
                            Name = "Crispy Chicken Fry",
                            PreparedStock = 0,
                            Price = 0m,
                            ProfitMargin = 0m
                        },
                        new
                        {
                            Id = 3,
                            Category = "French Fry",
                            Description = "Crispy golden french fries with salt",
                            ImageUrl = "/images/fries.jpg",
                            IsAvailable = true,
                            IsDeal = false,
                            IsDirectPurchase = false,
                            Name = "Golden French Fries",
                            PreparedStock = 0,
                            Price = 0m,
                            ProfitMargin = 0m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Noodles",
                            Description = "Stir-fried noodles with vegetables and spices",
                            ImageUrl = "/images/noodles.jpg",
                            IsAvailable = true,
                            IsDeal = false,
                            IsDirectPurchase = false,
                            Name = "Spicy Noodles",
                            PreparedStock = 0,
                            Price = 0m,
                            ProfitMargin = 0m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Mojo",
                            Description = "Refreshing mojo soft drink",
                            DirectPurchaseCost = 0m,
                            ImageUrl = "/images/mojo.jpg",
                            IsAvailable = true,
                            IsDeal = false,
                            IsDirectPurchase = true,
                            Name = "Mojo Drink",
                            PreparedStock = 0,
                            Price = 0m,
                            ProfitMargin = 0m
                        });
                });

            modelBuilder.Entity("FoodE_Backend.Model.MaterialPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("MaterialPurchases");
                });

            modelBuilder.Entity("FoodE_Backend.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodE_Backend.Model.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<string>("FoodItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FoodE_Backend.Model.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastPurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MinimumStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RawMaterials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 20m,
                            Name = "Burger Bun",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 2,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 20m,
                            Name = "Beef Patty",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 3,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 30m,
                            Name = "Cheese Slice",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 4,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 10m,
                            Name = "Lettuce",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 5,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 15m,
                            Name = "Tomato",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 6,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 10m,
                            Name = "Onion",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 7,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 20m,
                            Name = "Pickles",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 8,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 500m,
                            Name = "Ketchup",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 9,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 500m,
                            Name = "Mayonnaise",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 10,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 20m,
                            Name = "Chicken Pieces",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 11,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 1000m,
                            Name = "Flour",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 12,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 500m,
                            Name = "Breadcrumbs",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 13,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 12m,
                            Name = "Eggs",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 14,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 200m,
                            Name = "Spices Mix",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 15,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 1000m,
                            Name = "Cooking Oil",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 16,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 5m,
                            Name = "Potato",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 17,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 500m,
                            Name = "Salt",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 18,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 10m,
                            Name = "Noodles (Dry)",
                            Unit = "packet"
                        },
                        new
                        {
                            Id = 19,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 500m,
                            Name = "Mixed Vegetables",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 20,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 300m,
                            Name = "Soy Sauce",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 21,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 100m,
                            Name = "Garlic",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 22,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 100m,
                            Name = "Ginger",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 23,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 10m,
                            Name = "Chili",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 24,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 5m,
                            Name = "Spring Onion",
                            Unit = "bunch"
                        },
                        new
                        {
                            Id = 25,
                            CostPerUnit = 0m,
                            CurrentStock = 0m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MinimumStock = 20m,
                            Name = "Mojo Bottle",
                            Unit = "bottle"
                        });
                });

            modelBuilder.Entity("FoodE_Backend.Model.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId")
                        .IsUnique();

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("FoodE_Backend.Model.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("QuantityNeeded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");
                });

            modelBuilder.Entity("FoodE_Backend.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            Email = "admin@foode.com",
                            Name = "Admin User",
                            Password = "Admin@123",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("FoodE_Backend.Model.MaterialPurchase", b =>
                {
                    b.HasOne("FoodE_Backend.Model.RawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("FoodE_Backend.Model.OrderItem", b =>
                {
                    b.HasOne("FoodE_Backend.Model.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodE_Backend.Model.Recipe", b =>
                {
                    b.HasOne("FoodE_Backend.Model.FoodItem", "FoodItem")
                        .WithOne("Recipe")
                        .HasForeignKey("FoodE_Backend.Model.Recipe", "FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("FoodE_Backend.Model.RecipeIngredient", b =>
                {
                    b.HasOne("FoodE_Backend.Model.RawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodE_Backend.Model.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawMaterial");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FoodE_Backend.Model.FoodItem", b =>
                {
                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FoodE_Backend.Model.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FoodE_Backend.Model.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
