// <auto-generated />
using System;
using FoodE_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodE_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260227154129_AddAutoPricingSystem")]
    partial class AddAutoPricingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodE_Backend.Model.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DirectPurchaseCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDirectPurchase")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ProfitMargin")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Burgers",
                            Description = "Delicious beef burger with fresh vegetables",
                            ImageUrl = "/images/burger.jpg",
                            IsAvailable = true,
                            IsDeal = false,
                            IsDirectPurchase = false,
                            Name = "Beef Burger",
                            Price = 150m,
                            ProfitMargin = 0m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Chicken",
                            Description = "Crispy fried chicken",
                            ImageUrl = "/images/chicken.jpg",
                            IsAvailable = true,
                            IsDeal = false,
                            IsDirectPurchase = false,
                            Name = "Fried Chicken",
                            Price = 120m,
                            ProfitMargin = 0m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Sides",
                            Description = "Golden crispy french fries",
                            ImageUrl = "/images/fries.jpg",
                            IsAvailable = true,
                            IsDeal = false,
                            IsDirectPurchase = false,
                            Name = "French Fries",
                            Price = 80m,
                            ProfitMargin = 0m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Main Course",
                            Description = "Premium beef steak",
                            ImageUrl = "/images/steak.jpg",
                            IsAvailable = true,
                            IsDeal = false,
                            IsDirectPurchase = false,
                            Name = "Beef Steak",
                            Price = 250m,
                            ProfitMargin = 0m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Beverages",
                            Description = "Refreshing mojo drink",
                            DirectPurchaseCost = 20m,
                            ImageUrl = "/images/mojo.jpg",
                            IsAvailable = true,
                            IsDeal = false,
                            IsDirectPurchase = true,
                            Name = "Mojo Drink",
                            Price = 30m,
                            ProfitMargin = 10m
                        });
                });

            modelBuilder.Entity("FoodE_Backend.Model.MaterialPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("MaterialPurchases");
                });

            modelBuilder.Entity("FoodE_Backend.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodE_Backend.Model.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<string>("FoodItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FoodE_Backend.Model.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CostPerUnit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CurrentStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastPurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MinimumStock")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RawMaterials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CostPerUnit = 5m,
                            CurrentStock = 100m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 502, DateTimeKind.Local).AddTicks(6804),
                            MinimumStock = 0m,
                            Name = "Burger Bun",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 2,
                            CostPerUnit = 25m,
                            CurrentStock = 80m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2177),
                            MinimumStock = 0m,
                            Name = "Beef Patty",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 3,
                            CostPerUnit = 8m,
                            CurrentStock = 60m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2200),
                            MinimumStock = 0m,
                            Name = "Cheese Slice",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 4,
                            CostPerUnit = 2m,
                            CurrentStock = 50m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2202),
                            MinimumStock = 0m,
                            Name = "Lettuce",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 5,
                            CostPerUnit = 3m,
                            CurrentStock = 50m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2248),
                            MinimumStock = 0m,
                            Name = "Tomato",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 6,
                            CostPerUnit = 0.5m,
                            CurrentStock = 1000m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2287),
                            MinimumStock = 0m,
                            Name = "Sauce",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 7,
                            CostPerUnit = 40m,
                            CurrentStock = 50m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2289),
                            MinimumStock = 0m,
                            Name = "Chicken Breast",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 8,
                            CostPerUnit = 0.1m,
                            CurrentStock = 5000m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2292),
                            MinimumStock = 0m,
                            Name = "Flour",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 9,
                            CostPerUnit = 0.5m,
                            CurrentStock = 500m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2294),
                            MinimumStock = 0m,
                            Name = "Spices Mix",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 10,
                            CostPerUnit = 0.3m,
                            CurrentStock = 2000m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2296),
                            MinimumStock = 0m,
                            Name = "Oil",
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 11,
                            CostPerUnit = 5m,
                            CurrentStock = 200m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2298),
                            MinimumStock = 0m,
                            Name = "Potato",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 12,
                            CostPerUnit = 0.02m,
                            CurrentStock = 1000m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2300),
                            MinimumStock = 0m,
                            Name = "Salt",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 13,
                            CostPerUnit = 80m,
                            CurrentStock = 30m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2302),
                            MinimumStock = 0m,
                            Name = "Beef Steak Cut",
                            Unit = "piece"
                        },
                        new
                        {
                            Id = 14,
                            CostPerUnit = 0.8m,
                            CurrentStock = 200m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2304),
                            MinimumStock = 0m,
                            Name = "Black Pepper",
                            Unit = "gm"
                        },
                        new
                        {
                            Id = 15,
                            CostPerUnit = 0.5m,
                            CurrentStock = 500m,
                            IsActive = true,
                            LastPurchaseDate = new DateTime(2026, 2, 27, 21, 41, 27, 504, DateTimeKind.Local).AddTicks(2306),
                            MinimumStock = 0m,
                            Name = "Butter",
                            Unit = "gm"
                        });
                });

            modelBuilder.Entity("FoodE_Backend.Model.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId")
                        .IsUnique();

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2026, 2, 27, 21, 41, 27, 505, DateTimeKind.Local).AddTicks(3578),
                            FoodItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2026, 2, 27, 21, 41, 27, 505, DateTimeKind.Local).AddTicks(4253),
                            FoodItemId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2026, 2, 27, 21, 41, 27, 505, DateTimeKind.Local).AddTicks(4255),
                            FoodItemId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2026, 2, 27, 21, 41, 27, 505, DateTimeKind.Local).AddTicks(4257),
                            FoodItemId = 4
                        });
                });

            modelBuilder.Entity("FoodE_Backend.Model.RecipeIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("QuantityNeeded")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuantityNeeded = 1m,
                            RawMaterialId = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            QuantityNeeded = 1m,
                            RawMaterialId = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            QuantityNeeded = 2m,
                            RawMaterialId = 3,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 4,
                            QuantityNeeded = 1m,
                            RawMaterialId = 4,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 5,
                            QuantityNeeded = 1m,
                            RawMaterialId = 5,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 6,
                            QuantityNeeded = 20m,
                            RawMaterialId = 6,
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 7,
                            QuantityNeeded = 1m,
                            RawMaterialId = 7,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 8,
                            QuantityNeeded = 100m,
                            RawMaterialId = 8,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 9,
                            QuantityNeeded = 20m,
                            RawMaterialId = 9,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 10,
                            QuantityNeeded = 50m,
                            RawMaterialId = 10,
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 11,
                            QuantityNeeded = 2m,
                            RawMaterialId = 11,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 12,
                            QuantityNeeded = 5m,
                            RawMaterialId = 12,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 13,
                            QuantityNeeded = 100m,
                            RawMaterialId = 10,
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 14,
                            QuantityNeeded = 1m,
                            RawMaterialId = 13,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 15,
                            QuantityNeeded = 10m,
                            RawMaterialId = 14,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 16,
                            QuantityNeeded = 20m,
                            RawMaterialId = 15,
                            RecipeId = 4
                        },
                        new
                        {
                            Id = 17,
                            QuantityNeeded = 10m,
                            RawMaterialId = 6,
                            RecipeId = 4
                        });
                });

            modelBuilder.Entity("FoodE_Backend.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 9999,
                            Email = "admin@foode.com",
                            Name = "Admin User",
                            Password = "Admin@123",
                            Role = "admin"
                        });
                });

            modelBuilder.Entity("FoodE_Backend.Model.MaterialPurchase", b =>
                {
                    b.HasOne("FoodE_Backend.Model.RawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("FoodE_Backend.Model.OrderItem", b =>
                {
                    b.HasOne("FoodE_Backend.Model.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodE_Backend.Model.Recipe", b =>
                {
                    b.HasOne("FoodE_Backend.Model.FoodItem", "FoodItem")
                        .WithOne("Recipe")
                        .HasForeignKey("FoodE_Backend.Model.Recipe", "FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");
                });

            modelBuilder.Entity("FoodE_Backend.Model.RecipeIngredient", b =>
                {
                    b.HasOne("FoodE_Backend.Model.RawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodE_Backend.Model.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RawMaterial");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("FoodE_Backend.Model.FoodItem", b =>
                {
                    b.Navigation("Recipe")
                        .IsRequired();
                });

            modelBuilder.Entity("FoodE_Backend.Model.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FoodE_Backend.Model.Recipe", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
